### ISSUE TITLE
 plex_exporter_importer.py: Allow alternate name of exported/importing posters/images

### ISSUE THREAD

**Issue by gitttt54** [Casvt/Plex-scripts#107]
Hello,

coming from [here](https://github.com/Casvt/Plex-scripts/issues/74#issuecomment-1158241479),
I'd like to request an additional feature for the great  poster_exporter_importer script.

Can you add an option to define the artist and album image name?
Like -`-AlbumImageName cover_front.jpg` and `--ArtistImageName Artist.jpg`
So users can define their own filenames to be imported (and maybe exported).

Its simply because:
I can not rename all the images, because other software scripts won't work then.
And I share (better, they share with me) folders with friends, which surely have their own scripts and would not like me to rename all their image files.

Thank you!

**Comment by Casvt** [comment]
Hey, your request is completed, but in a different way than you think.

I've made a whole new script just to do what you want, because it's easier this way (trust me). You can find it here: https://github.com/Casvt/Plex-scripts/blob/main/changing_settings/poster_exporter_importer.py.

It does exactly what you want it to do:

- Export: Select the media, what you want to export (poster and/or background), and if you want to, a custom name for the resulting file (instead of 'poster' and 'background').
- Import: Select the media, what you want to import (poster and/or background), and if you want to, a custom name for the file to search for. This is what you want.

You could run it like this:
```shell
python3 poster_exporter_importer.py --Type "import" --Process "poster" --NoEpisodePoster --PosterName "cover_front" --AllMusic
```
This will import the external poster files (not backgrounds) that are called "cover_front.xyz" for all music libraries.

Hope this is what you want! Let me know if you have any questions or additional requests \:\)

**Comment by gitttt54** [comment]
Thank you very much!! VERY appreciated! 
I'll will now try to set up a linux with python3 and try/test your fine script. 
Thank you also for the example in your post. That will help a lot.

Have a great time!

And yes, I trust you ;-D

**Comment by Casvt** [comment]
No problem. It's better this way than to use a different script for different purposes in a kind of weird unintended way.

> I will now try to set up a linux with python3 and try/test your fine script.

You know python scripts can run on windows and MacOS too right? No need to setup a whole Linux OS just to run a python script. Unless you were already doing it for other reasons. Just wanted to let you know.

**Comment by gitttt54** [comment]
> You know python scripts can run on windows and MacOS too right? No need to setup a whole Linux OS just to run a python script. Unless you were already doing it for other reasons. Just wanted to let you know.

Thank you,
the plex server is an Unraid Linux, which I don't want to break the core, while installing anything on the host system.
(Also, I try not to break anything, because I'm not the only "admin" here...)
It should be easy to set up a Linux Debian VM which only purpose is to run some plex scripts.
I have had tried a lot of tools for installing any kind of linux tools to MacOS, but they only worked until the next MacOS update killed them again and again. So I stopped using my Mac and now have Linux VMs for my special needs.

**Comment by Casvt** [comment]
Alright 👍 python3 is built in into most Linux distros so no problems with setting it up in a Linux vm
