### ISSUE TITLE
sonarr_refresh_tba.py: Doesn't actually refresh 

### ISSUE THREAD

**Issue by lamepennies** [Casvt/Plex-scripts#116]
In which file is the bug?
[sonarr_refresh_tba.py](https://github.com/Casvt/Plex-scripts/blob/main/sonarr/sonarr_refresh_tba.py)

Describe the setup (arguments and their values, how it was run, etc.):
My sonarr is connected via the API and listing fine in terminal

Describe what the bug is:
Sonarr isn't refreshing the series listed in terminal

Describe what _should_ be happening:
I'm noticing that in terminal it does list the shows that need a refresh but sonarr isn't actually refreshing those series. I did a test where Man vs Bee was all TBA and ran the script. It listed fine but Sonarr wasn't refreshed. When I manually refreshed, it updated to say Chapter 1... Same thing with Money Heist: Korea - Joint Economic Area, the script just listed it in terminal but no refresh.

**Comment by lamepennies** [comment]
To add to this ticket, with the updated script, plex just lists and doesn't trigger an actual refresh metadata. At least on mine.

**Comment by Casvt** [comment]
Seeing that the problem shows at both Plex and sonarr, it's probably something with the general web requesting instead of specific requests.

1. Do you connect to sonarr and Plex using https? 
2. Do you access sonarr and Plex using a hostname or even domain name?
3. Do you need to access the web-ui via an url-prefix? (e.g. `192.168.2.15/sonarr`)

Basically, _anything_ special with your setup?

**Comment by Casvt** [comment]
Another question: do you have your python dependencies fully updated? Try and then re-run the script:
```shell
python3 -m pip install --upgrade requests
```

**Comment by lamepennies** [comment]
Hey Cast,
I'm accessing via a domain. There are no errors in terminal when I execute, it just lists the series that need updating. That's why I think it's not triggering it. And yes, requests is installed and up to date
