### ISSUE TITLE
recent_episode_maintainer.py: More filters, preview and sonarr/radarr integration

### ISSUE THREAD

**Issue by Desy10140** [Casvt/Plex-scripts#172]
- Find and delete media
- User defined filters for finding media
- Filters should include: # of days since last play, Date added, Watched/not watched, File Size, Resolution, Bitrate
- Preview list of media that meet filters
- Delete media and remove from monitoring
- A version that would be compatible with Tautulli scripts for scheduled running, effectively creating a data retention policy for media

This would be the same as combining Tautulli's library media view with Plex watch data and filtering with Sonarr/Radarr's mass edit feature.

**Comment by Casvt** [comment]
It sounds like it would be smarter to add these things as features to the [recent_episode_maintainer.py](https://github.com/Casvt/Plex-scripts/blob/main/media_management/recent_episode_maintainer.py) script. 
1. Filter: "Delete media on or before a certain date". NOTE: `--DaysAdded` is already available, which deletes media that was added more than N days ago. `--DaysAdded` is relative in time, while this new feature would be absolute in time. Is that what you want?
2. Filter: "Delete media if it's watched/not watched"
3. Filter: "Delete media if it's above/below N mb in size"
4. Filter: "Delete media if it's above/below a certain resolution"
5. Filter: "Delete media if it's above/below a certain bitrate"
6. Ability to preview what media is affected, without actually doing something.
7. Ability to change filter relation from OR to AND. Aka instead of "filter1 or filter2 or filter3", "filter1 and filter2 and filter3".
8. Connection to sonarr/radarr to allow unmonitoring the affected media.

The rest of your requests can already be done with the current version of the script.

**Comment by Desy10140** [comment]
Oh, that would be great!

I didn't look at that existing script, the name is a bit misleading.
