### ISSUE TITLE
Plex_exporter_importer:by date

### ISSUE THREAD

**Issue by RBeatse** [Casvt/Plex-scripts#24]
> Only one feature should be requested per issue. Please make multiple issues if you have multiple feature requests

In what file should the feature be added? Plex_exporter_importer

What is the feature request?
For a large set of libraries, this script can run for a while. That is to be expected the first time but the next time it is run, it would be great to be able to have it only extract info on items that have been added or updated since "x" date (in whatever format is needed) or in the last x days (which would be nice for automating a script to run every week or something.

**Comment by Casvt** [comment]
By the time we check what the last "updated" time was, we already have the info to update the file. Your underlying request is "making it faster or less recourse intensive" because you want to run it at an interval (which I support). I think that optimizing the script will reduce load and slowness enough to make it worth it to run it at an interval. Just trust me for a second and wait until I've made the optimized version. Let's look again after that release eh?

**Comment by Casvt** [comment]
I'm going to close this issue and redirect you to issue #14 where you requested speed improvements. You can always open a new issue afterwards if it's still not good enough.
