### ISSUE TITLE
Script to set TV shows "auto delete after watching" under the series advanced settings

### ISSUE THREAD

**Issue by RileyXX** [Casvt/Plex-scripts#43]
Script to automatically set the "delete after 1 week" option under each TV series advanced settings. Script should be able to be easily edited for each of the options listed. To delete after x amount of days/week. 

This wasnt originally my idea but from someone else on [reddit](https://www.reddit.com/r/PleX/comments/uu7llh/comment/i9ecjpr/) . I like the idea and I've been trying to figure out a simple way to do this. Because it sucks having to go through and set this setting in plex everytime a new series is added. I always have to go through and check all my series to make sure this option is checked.

**Comment by Casvt** [comment]
Script completed. You can find it here: https://github.com/Casvt/Plex-scripts/blob/main/various/plex_auto_delete.py

**Comment by erikt311** [comment]
Something is happening where this script is actually causing media to be deleted instead of just marking it to be deleted later. I can watch a bunch of episodes in Plex, run this script, and immediately see the episodes I just watched move to my recycle bin (windows). 

I wouldn't expect that to happen. They shouldn't be deleted until 24 hrs (or whatever I set) after watching them. 

What plex logs would be helpful to determine what is happening here? I can't seem to track down what is actually doing the deletion and why.

**Comment by Casvt** [comment]
Under the series settings -> advanced -> "delete episodes after watching" (name could be a little different; I have my Plex server set to Dutch so I had to translate roughly), set it to "after a day".

Oh I think I know why. Media gets deleted a day after being watched. If you've watched some of the media, let's say, a week ago, then now in the present, it has been more than 24 hours since it has been watched so it immediately gets deleted.

**Comment by ChipSkylark37** [comment]
Using this resulted in an error for me.

**Command used:**
plex_auto_delete.py -v after_week -l "TV Shows"

**Resulted in the following:**
C:\bkup>plex_auto_delete.py -v after_week -l "TV Shows"
TV Shows
    SHOW NAME
Traceback (most recent call last):
  File "C:\bkup\plex_auto_delete.py", line 114, in <module>
    plex_auto_delete(
  File "C:\bkup\plex_auto_delete.py", line 87, in plex_auto_delete
    params={'autoDeletionItemPolicyWatchedLibrary': value.value}
AttributeError: 'str' object has no attribute 'value'

**Modifying the block from:**

plex_auto_delete(
    ssn, args.Value,
    args.LibraryName, args.SeriesName
)

**TO:**

plex_auto_delete(
    ssn, ValueMapping[args.Value],
    args.LibraryName, args.SeriesName
)

seemingly fixed this issue, upon running I saw it mark for all shows and start removing watched files.

**Comment by Casvt** [comment]
Fixed the bug
