### ISSUE TITLE
Delete files and unmonitor based on tag

### ISSUE THREAD

**Issue by theotocopulitos** [Casvt/Plex-scripts#60]
My proposal:

I have a two instances setup (1080p and 4K). I use plex-meta-manager to tag (“4K”) the movies in 1080p that I get in 4K, and then I want to delete the 1080p movies, but keep the movie in radarr, as unmonitored.

To do so, I filter all the movies in radarr with “4K” tag… and… ooops! I can delete all movies from radarr, but that would remove the whole entry, not just the files. So I have to painstakingly go movie by movie and delete the files one at a time

So my dream script would delete all files in all movies with a given tag (and additionally unmonitor them!)

**Comment by Casvt** [comment]
To make it clear: So you have movies in 1080p. Then when you upgrade to a 4k version, you have a 1080p and a 4k version of the same movie and because you downloaded a 4k movie, the movie in radarr has the "4k" tag added. Now you want a script that searches for this "4k" tag and delete all movies in it but not the movie entry in radarr? Why would you want to delete both your 1080p and 4k version?

Or do you mean that you have two radarr instances (r1 = 1080p and r2 = 4k instance)? r1 downloads a 1080p movie, but r2 downloads a 4k version. When the 4k version is downloaded, a "4k" tag is added to the movie at the r1 instance. You want a script that searches for this "4k" tag in r1 and delete the file which deletes the 1080p version but not the 4k version. Is this correct?

Just a bit confused

**Comment by theotocopulitos** [comment]
Ok. I used the 4K/1080p as an example that I thought would be easier. But in fact it isn’t, because, yes, to keep only 4K I could use just one instance.

Let me explain exactly my setup, and then what I need the script to do

I watch movies with  original audio (whatever it is) [OV - original version], but family wants them in Spanish. So I get many every movie in OV (easier to get), and then in DUAL version for my family as they become available. I use Plex to see them, so I have two different libraries, from folders Movies-VO and Movies-DUAL respectively. I can access both libraries from my user, but my family only get to see movies under Movies-DUAL.

To achieve this I have two radarr instances. One (say, r1) gets my movies into Movies-VO (r2), and the other one gets them into Movies-DUAL, when they become available. I do not need two versions of the movies that come into Movies-DUAL, so when I get them, I delete the corresponding files for that movie under Movies-VO, but I want to keep the movie entry in r1, but unmonitored.

To get there, as of today, I run plex-meta-manager every night, with which I can get every movie in r2, and if it is un r1, tag the movie entry as “Dual” in r1. 
Then I go into r1, filter movies by tag “Dual” and then unmonitor all of them. Now I cannot bat he delete all files for these movies from r1 in a batch (I can delete the movie files and the movies entry from r1, but only deleting the whole movie entry, which I don’t want). So I need to go to the details page of each Movie in r1 and there delete the associated files from there, one by one. 

So, I need the script to filter all movies in r1 with a given tag (say “Dual”), and then the script could unmonitor those movies in r1, and finally remove all movie files, for all these movies.

**Comment by Casvt** [comment]
Oh okay so: "Delete the movie files and unmonitor the movies that have a certain tag". Is it just that easy? I can make this in _minutes_.

**Comment by theotocopulitos** [comment]
That easy! Thanks!

**Comment by Casvt** [comment]
Request completed. You can find the script here: https://github.com/Casvt/Plex-scripts/blob/main/radarr/delete_unmonitor_on_tag.py. Enjoy!

**Comment by theotocopulitos** [comment]
I don't know if this is the place to comment...

The delete option works like a charm. But I cannot get the unmonitor option to work: it just prints out the movies names, but their status in radarr do not change...

**Comment by Casvt** [comment]
Do you have `-u` or `--UnmonitorMovie` in your arguments? Just getting the obvious out of the way...

**Comment by Casvt** [comment]
Tested it out. Works perfectly fine for me.

**Comment by theotocopulitos** [comment]
Yes…!

**Comment by Casvt** [comment]
Well then it's very weird why it isn't working. Can you contact me using the discord server (https://discord.gg/QvWKGJ86XR)? I'll make a special version of the script tomorrow (22:30 here now) that'll you can run once and share the output of which will give me more information to why it isn't working. Sorry for the problems but it works for me so I can't figure out what's going wrong without information coming from you.

**Comment by theotocopulitos** [comment]
Ok! Thanks

**Comment by Casvt** [comment]
Hey, if you want to, we can also just do it now together without me making a special version.

**Comment by theotocopulitos** [comment]
That's fine for me!

**Comment by Casvt** [comment]
Please go into the file and go to lines 50-53. Please edit the code there so that it'll look like the picture below. The indentation is done using tabs.

![delete_unmonitor_on_tag_DEBUG_PICTURE](https://user-images.githubusercontent.com/88994465/169903239-1dcf45ec-8ed2-47b6-8470-f3e89d3205c6.png)

**Comment by Casvt** [comment]
When you've edited the script so that it looks like the image above, run the script again. You should now get a pretty big output on your terminal. Please share this output. You can share it to me in any way you want: paste into github comment, share file on github, share file on discord, paste into discord. However you want.

**Comment by theotocopulitos** [comment]
```
The Curse of the Jade Scorpion
415
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
  "title": "Unsupported Media Type",
  "status": 415,
  "traceId": "00-ad510396c4d7ae4ef02f2e3347336a8d-2060fa9df5099853-00"
}
```

**Comment by Casvt** [comment]
Great. Thanks alot

**Comment by theotocopulitos** [comment]
Tried a different instance, got the same result... (my 4k radarr instance)

**Comment by Casvt** [comment]
Run the following command in a terminal: `python3 -m pip install requests --upgrade`. Then try again (I don't need the output, just need to know if it works).

**Comment by theotocopulitos** [comment]
No :(

Same error

**Comment by Casvt** [comment]
I'm baffled. `data=movie` creates the same error that you have but that's not what's in the script. Inside the script we use `json=movie` which _should_ and _does_ work fine for me and yet not for you?? I'm still investigating

**Comment by theotocopulitos** [comment]
No worries! The most important part, the deletion, works beautifully

**Comment by Casvt** [comment]
No but I can't stand that I execute a command and it works fine and you do exactly the same thing and it doesn't work. _That doesn't make sense._ I want it to work but I'm just really not sure what's going on. A feature of the requests library is behaving differently for you than it is for me which shouldn't be. Making you execute that command above updated the library to the newest version just like I have, so that means that we both have the same version.

We have the same library, the same version, the same request, the same data and yet when you do it you get a different result than that I get. It must be radarr right? Our scripts and libraries are exactly the same, so maybe it's radarr? Take a look at the logs and maybe you find something?

**Comment by theotocopulitos** [comment]
This is all I can get from the logs:

`2022-05-23 23:25:00.5|Debug|Api|[PUT] /api/v3/movie/2475?apikey=(removed) 415.UnsupportedMediaType (5 ms)
2022-05-23 23:25:00.5|Debug|Api|[PUT] /api/v3/movie/2729?apikey=(removed) 415.UnsupportedMediaType (0 ms)
2022-05-23 23:25:00.5|Debug|Api|[PUT] /api/v3/movie/3252?apikey=(removed) 415.UnsupportedMediaType (0 ms)`

I am not sure if the numbers after "movie" are correct... for instance in radarr one of those movies has the url: 
radarrserver/movie/17917    . Is this number the movie(id) that should appear in the api/v3/movid(id) path? or not...

Well too late for tonight. Thanks for the help!

**Comment by theotocopulitos** [comment]
Just for the record. I am not sure if I said this before. I am running Version 4.1.0.6175 of radarr

**Comment by Casvt** [comment]
> I am not sure if the numbers after "movie" are correct...

Yes they are correct. Better said, it's correct that they don't match up. That part is working correctly.

> I am running Version 4.1.0.6175 of radarr

Well I'm too. I'm going to sleep over it and come back tomorrow with a fresh mind

**Comment by theotocopulitos** [comment]
This is crazy. If I type

`curl -L -X GET http://radarr.rivendel.me/api/v3/movie/17943?apikey=*edited* -H "accept: application/json" -o print.txt`

edit print.txt to change monitored to false and then do

`curl -L -X GET http://radarr.rivendel.me/api/v3/movie/17943?apikey=*edited*  -H "accept: text/plain" -o print.txt`

it correctly changes the monitored status

**Comment by Casvt** [comment]
Well that's peculiar. Why does radarr except JSON data when content type is set to text/plain? This keeps getting weirder and weirder
