### ISSUE TITLE
plex_exporter_importer.py: Allow arbitrary export location

### ISSUE THREAD

**Issue by chazlarson** [Casvt/Plex-scripts#95]
In what file should the feature be added?
plex_exporter_importer.py

What is the feature request?
I don't have write access to my media store, so can't write the metadata backup file next to each movie.  I'd like the option to write it to the local directory where the script is running, which would also allow it to run remote from the plex server.

**Comment by Casvt** [comment]
Request completed. The script has been updated a lot and now works with one database file instead of thousands of files along side the media. This database file, can be created anywhere and can be moved around. This means that your request has been fulfilled. By default, the database file is created in the same folder as the script.
